
export const regionesMunicipios = {
  todos: ["pará"],
    
  regiões: [
    "baixo amazonas",
    "baixo tocantins",
    "araguaia",
    "caeté",
    "capim",
    "carajás",
    "guajarina",
    "lago tucuruí",
    "marajó",
    "metropolitano",
    "salgado",
    "tapajós",
    "xingu",
  ],
  "baixo amazonas": ["santarém", "juruti","oriximiná","prainha"],
  "baixo tocantins": ["barcarena", "abaetetuba"],
  araguaia: ["são félix do xingu"],
  caeté: ["bragança", "augusto correa", "tracuateua"],
  capim: ["paragominas", "dom eliseu"],
  carajás: ["parauapebas", "itupiranga"],
  guajarina: ["castanhal","magalhães barata"],
  "lago tucuruí": ["tucuruí", "goianésia"],
  marajó: [
    "portel",
    "soure",
    "bagre",
    "muaná",
    "gurupá",
    "oeiras",
    "boavistense",
  ],
  metropolitano: ["belem", "ananindeua", "marituba", "benevides"],
  salgado: ["salinas", "curuçá"],
  tapajós: ["itaituba"],
  xingu: ["altamira","vitoria do xingu"],
};

export const municipioLinks = {
  "baixo amazonas": "https://www.enoticiapara.com.br/regiao/baixo-amazonas",
  "baixo tocantins": "https://www.enoticiapara.com.br/regiao/baixo-tocantins",
  araguaia: "https://www.enoticiapara.com.br/regiao/araguaia",
  caeté: "https://www.enoticiapara.com.br/regiao/caete",
  capim: "https://www.enoticiapara.com.br/regiao/capim",
  carajás: "https://www.enoticiapara.com.br/regiao/carajas",
  guajarina: "https://www.enoticiapara.com.br/regiao/guajarina",
  "lago tucuruí": "https://www.enoticiapara.com.br/regiao/lago-tucurui",
  marajó: "https://www.enoticiapara.com.br/regiao/marajo",
  metropolitano: "https://www.enoticiapara.com.br/regiao/metropolitana",
  salgado: "https://www.enoticiapara.com.br/regiao/salgado",
  tapajós: "https://www.enoticiapara.com.br/regiao/tapajos",
  xingu: "https://www.enoticiapara.com.br/regiao/xingu",
  pará: "https://www.enoticiapara.com.br",
  santarém: "https://www.enoticiasantarem.com.br",
  juruti: "https://www.enoticiajuruti.com.br",
  barcarena: "https://www.enoticiabarcarena.com.br",
  abaetetuba: "https://www.enoticiaabaetetuba.com.br",
  bragança: "https://www.enoticiabraganca.com.br",
  paragominas: "https://www.enoticiaparagominas.com.br",
  parauapebas: "https://www.enoticiaparauapebas.com.br",
  castanhal: "https://www.enoticiacastanhal.com.br",
  tucuruí: "https://www.enoticiatucurui.com.br",
  portel: "https://www.enoticiaportel.com.br",
  soure: "https://www.enoticiasoure.com.br",
  bagre: "https://www.enoticiabagre.com.br",
  muaná: "https://www.enoticiamuana.com.br",
  belem: "https://www.enoticiabelem.com.br",
  marituba: "https://www.enoticiamarituba.com.br",
  benevides: "https://www.enoticiabenevides.com.br",
  salínopolis: "https://www.enoticiasalinopolis.com.br",
  curuçá: "https://www.enoticiacuruca.com.br",
  itaituba: "https://www.enoticiaitaituba.com.br",
  altamira: "https://www.enoticiaaltamira.com.br",
  ananindeua: "https://www.enoticiaananindeua.com.br",
  "vitoria do xingu": "https://www.enoticiavitoriadoxingu.com.br",
  oeiras: "https://www.enoticiaoeiras.com.br",
  boavistense: "https://www.enoticiaboavistense.com.br",
  gurupá: "https://www.enoticiagurupa.com.br",
  tracuateua: "https://www.enoticiatracuateua.com.br",
  goianésia: "https://www.enoticiagoianesia.com.br",
  "augusto correa": "https://www.enoticiaaugustocorrea.com.br",
  salinas: "https://www.enoticiasalinas.com.br",
  itupiranga: "https://www.enoticiaitupiranga.com.br",
  "dom eliseu": "https://www.enoticiadomeliseu.com.br",

};

